version: "3.9"
services:
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      VPN_SERVICE_PROVIDER: nordvpn
      VPN_TYPE: openvpn
      OPENVPN_USER: ${VPN_USERNAME}
      OPENVPN_PASSWORD: ${VPN_PASSWORD}
      OPENVPN_PROTOCOL: udp
      SERVER_COUNTRIES: United States
      TZ: America/Los_Angeles
    volumes:
      - "${CONFIG_DIRECTORY}/gluetun:/gluetun"

    # qBittorrent shares Gluetun's network namespace,
    # so its Web UI port is exposed HERE.
    ports:
      - "8080:8080"

    restart: unless-stopped


  qbittorrent-vpn:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent

    # All qBittorrent networking goes through Gluetun.
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: America/Los_Angeles
      WEBUI_PORT: 8080
    volumes:
      - "${CONFIG_DIRECTORY}:/config"
      - "${DATA_DIRECTORY}:/media/data"
    restart: unless-stopped  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: US/Pacific
    dns: 8.8.8.8 # for some reason, the sonarr image has dns issues. just use google's for now...
    volumes:
      - "${DATA_DIRECTORY}:/media/data"
      - "${CONFIG_DIRECTORY}/sonarr:/config"
    ports:
      - "8989:8989"
  radarr:
    container_name: radarr
    restart: unless-stopped
    ports:
     - "7878:7878"
    volumes:
      - ${CONFIG_DIRECTORY}/radarr:/config
      - ${DATA_DIRECTORY}:/media/data
    environment:
      PUID: 1000
      PGID: 1000
      TZ: US/Pacific
    image: lscr.io/linuxserver/radarr:latest
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: US/Pacific
    volumes:
      - ${CONFIG_DIRECTORY}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    volumes:
      - ${CONFIG_DIRECTORY}/lidarr:/config
      - ${DATA_DIRECTORY}:/media/data
    ports:
      - 8686:8686
    restart: unless-stopped
  # Soulseek daemon for music I can't find with lidarr alone
  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - 5030:5030
      - 5031:5031
      - 50300:50300
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ${CONFIG_DIRECTORY}/slskd:/app
      - ${DATA_DIRECTORY}:/media/data
    restart: unless-stopped
